### ISSUE TITLE
Instagram is not a function

### ISSUE THREAD

**Issue by fsebbah** [guilhermefarias/instagram-api#1]
I installed the package via npm and I have this message:
mead@0.0.0 /var/www/mead
+-- config@1.20.1  extraneous
`-- nconf@0.8.4  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

/var/www/mead/routes/popular.js:9
    var InstagramAPI = require('instagram-api');
    var instagramAPI = new InstagramAPI(accessToken);
                      ^

TypeError: InstagramAPI is not a function
    at Object.<anonymous> (/var/www/mead/routes/popular.js:9:24)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/mead/app.js:38:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

Thanks,
Franck

**Comment by guilhermefarias** [comment]
Hello Franck, try to download the new version that I released this morning, was a little after you open this issue, the problem has been fixed! :+1:

**Comment by fsebbah** [comment]
Hi,
thanks for the response.
Ok, i tried and i send you a feedback.
